### ISSUE TITLE
Ignore case of runParameters.xml

### ISSUE THREAD

**Issue by donkirkby** [cfe-lab/MiSeqQCReport#25]
The data from the CDC Miseq uses the name `RunParameters.xml` instead of `runParameters.xml`, and that causes the QC upload to fail. Our Miseq will be upgraded soon, so it will probably be a problem for our data as well.

Just check for both possible names when uploading.

**Comment by rmcclosk** [comment]
@donkirkby Is this the one you wanted me to look into?

**Comment by donkirkby** [comment]
Yes please, @rmcclosk.

**Comment by rmcclosk** [comment]
Would you rather it be uploaded as `runParameters.xml`, or with the same name as it had coming in?
